openapi: 3.2.0
info:
  title: Cognite Labels API
  description: '# Introduction

    This is the reference documentation for the Cognite API with

    an overview of all the available methods.'
  version: v1
  contact:
    name: Cognite Support
    url: https://support.cognite.com
    email: support@cognite.com
servers:
- url: https://{cluster}.cognitedata.com/api/v1/projects/{project}
  description: The URL for the CDF cluster to connect to
  variables:
    cluster:
      enum:
      - api
      - az-tyo-gp-001
      - az-eastus-1
      - az-power-no-northeurope
      - westeurope-1
      - asia-northeast1-1
      - gc-dsm-gp-001
      default: api
      description: The CDF cluster to connect to
    project:
      default: publicdata
      description: The CDF project name.
security:
- oidc-token:
  - https://{cluster}.cognitedata.com/.default
- oauth2-client-credentials:
  - https://{cluster}.cognitedata.com/.default
- oauth2-open-industrial-data:
  - https://api.cognitedata.com/.default
- oauth2-auth-code:
  - https://{cluster}.cognitedata.com/.default
tags:
- name: Labels
paths:
  /labels:
    post:
      tags:
      - Labels
      summary: Create label definitions
      description: '> **Required capabilities:** `labelsAcl:WRITE`


        Creates label definitions that can be used across different resource types. The label definitions are uniquely identified by their external id.'
      operationId: createLabelDefinitions
      requestBody:
        description: List of label definitions to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalLabelDefinitionList'
        required: true
      responses:
        '201':
          $ref: '#/components/responses/LabelDefinitionCreateResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - labelsAcl:WRITE
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: "const labels = [\n  { externalId: 'PUMP', name: \"Pump\" },\n  { externalId: 'ROTATING_EQUIPMENT', name: 'Rotating equipment', description: 'Asset with rotating parts' }\n];\nconst createdLabels = await client.labels.create(labels);"
      - lang: Python
        label: Python SDK
        source: 'from cognite.client.data_classes import LabelDefinitionWrite

          labels = [LabelDefinitionWrite(external_id="ROTATING_EQUIPMENT", name="Rotating equipment"), LabelDefinitionWrite(external_id="PUMP", name="pump")]

          res = client.labels.create(labels)

          '
      - lang: Java
        label: Java SDK
        source: "List<Label> upsertLabelsList =  List.of(Label.newBuilder() \n          .setExternalId(\"10\") \n          .setName(\"Label name\") \n          .setDescription(\"Description\") \n          .build()); \n\nList<Label>  list = client.labels().upsert(upsertLabelsList); \n\n"
  /labels/list:
    post:
      tags:
      - Labels
      summary: Filter labels
      description: '> **Required capabilities:** `labelsAcl:READ`


        Use advanced filtering options to find label definitions.'
      operationId: listLabels
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelDefinitionListScope'
      responses:
        '200':
          $ref: '#/components/responses/LabelDefinitionListResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - labelsAcl:READ
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: 'const labels = await client.labels.list({ filter: { externalIdPrefix: ''Pu''}});'
      - lang: Python
        label: Python SDK
        source: "label_list = client.labels.list(limit=5, name=\"Pump\")\n\nfor label in client.labels:\n    label # do something with the label definition\n\nfor label_list in client.labels(chunk_size=2500):\n    label_list # do something with the type definitions\n"
      - lang: Java
        label: Java SDK
        source: "List<Label> listLabelsResults = new ArrayList<>(); \nclient.labels() \n          .list() \n          .forEachRemaining(labels -> listLabelsResults.addAll(labels)); \n\nclient.labels() \n          .list(Request.create() \n               .withFilterParameter(\"externalIdPrefix\", \"Val\")) \n          .forEachRemaining(labels -> listLabelsResults.addAll(labels)); \n\n"
  /labels/byids:
    post:
      tags:
      - Labels
      summary: Retrieve labels
      description: '> **Required capabilities:** `labelsAcl:READ`


        Retrieve labels using their external ids'
      operationId: byIdsLabels
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelsIdsWithIgnoreUnknownIds'
      responses:
        '200':
          $ref: '#/components/responses/LabelDefinitionListResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - labelsAcl:READ
      x-code-samples:
      - lang: Python
        label: Python SDK
        source: 'res = client.labels.retrieve(external_id="my_label", ignore_unknown_ids=True)

          '
  /labels/delete:
    post:
      tags:
      - Labels
      summary: Delete label definitions
      description: '> **Required capabilities:** `labelsAcl:WRITE`


        Delete all the label definitions specified by their external ids. The resource items that have the corresponding label attached remain unmodified. It is up to the client to clean up the resource items from their attached labels if necessary.'
      operationId: deleteLabels
      requestBody:
        description: List of external ids of label definitions to delete.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelDefinitionExternalIdList'
        required: true
      responses:
        '200':
          $ref: '#/components/responses/EmptyResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - labelsAcl:WRITE
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: 'await client.labels.delete([{externalId: ''PUMP''}, {externalId: ''VALVE''}]);'
      - lang: Python
        label: Python SDK
        source: 'client.labels.delete(external_id=["big_pump", "small_pump"])

          '
      - lang: Java
        label: Java SDK
        source: "List<Item> deleteItemsByExternalIds = List.of(Item.newBuilder() \n          .setExternalId(\"10\") \n          .build()); \nList<Item> deleteItemsResults = \n          client.labels().delete(deleteItemsByExternalIds); \n\nList<Item> deleteItemsByInternalIds = List.of(Item.newBuilder() \n          .setId(10) \n          .build()); \nList<Item> deleteItemsResults = \n          client.labels().delete(deleteItemsByInternalIds); \n\n"
components:
  schemas:
    Error:
      type: object
      required:
      - code
      - message
      description: Cognite API error.
      properties:
        code:
          type: integer
          description: HTTP status code.
          format: int32
          example: 401
        message:
          type: string
          description: Error message.
          example: Could not authenticate.
        missing:
          type: array
          description: List of lookup objects that do not match any results.
          items:
            type: object
            additionalProperties: true
        duplicated:
          type: array
          description: List of objects that are not unique.
          items:
            type: object
            additionalProperties: true
    Limit:
      type: object
      properties:
        limit:
          description: Limits the number of results to return.
          type: integer
          default: 100
          minimum: 1
          maximum: 1000
    ExternalLabelDefinitionList:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          minItems: 1
          maxItems: 1000
          uniqueItems: true
          items:
            $ref: '#/components/schemas/ExternalLabelDefinition'
    LabelsIdsWithIgnoreUnknownIds:
      type: object
      allOf:
      - type: object
        required:
        - items
        properties:
          items:
            type: array
            items:
              $ref: '#/components/schemas/LabelSelectByExternalId'
            minItems: 1
            maxItems: 1000
      - $ref: '#/components/schemas/IgnoreUnknownIdsField'
    Cursor:
      type: object
      properties:
        cursor:
          type: string
          example: 4zj0Vy2fo0NtNMb229mI9r1V3YG5NBL752kQz1cKtwo
      description: 'Cursor for paging through results. In general, if a response contains a `nextCursor`

        property, it means that there may be more results, and you should pass that value as the

        `cursor` parameter in the next request.


        Note that the cursor may or may not be encrypted, but either way, it is not intended to be

        decoded. Its internal structure is not a part of the public API, and may change without

        notice. You should treat it as an opaque string and not attempt to craft your own cursors.

        '
    DataSetInternalId:
      type: object
      title: DataSetInternalId
      required:
      - id
      properties:
        id:
          $ref: '#/components/schemas/CogniteInternalId'
    LabelDefinition:
      allOf:
      - $ref: '#/components/schemas/ExternalLabelDefinition'
      - type: object
        required:
        - createdTime
        properties:
          createdTime:
            $ref: '#/components/schemas/EpochTimestamp'
    EpochTimestamp:
      description: The number of milliseconds since 00:00:00 Thursday, 1 January 1970, Coordinated Universal Time (UTC), minus leap seconds.
      type: integer
      minimum: 0
      format: int64
      example: 1730204346000
    IgnoreUnknownIdsField:
      type: object
      properties:
        ignoreUnknownIds:
          description: Ignore IDs and external IDs that are not found
          type: boolean
          default: false
    LabelDefinitionCreateList:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          minItems: 1
          maxItems: 1000
          uniqueItems: true
          items:
            $ref: '#/components/schemas/LabelDefinition'
    DataSetExternalId:
      type: object
      title: DataSetExternalId
      required:
      - externalId
      properties:
        externalId:
          $ref: '#/components/schemas/CogniteExternalId'
    CogniteInternalId:
      description: A server-generated ID for the object.
      type: integer
      minimum: 1
      maximum: 9007199254740991
      format: int64
    LabelDefinitionListScope:
      allOf:
      - $ref: '#/components/schemas/LabelDefinitionFilter'
      - $ref: '#/components/schemas/Cursor'
      - $ref: '#/components/schemas/Limit'
    LabelDefinitionExternalId:
      type: object
      required:
      - externalId
      properties:
        externalId:
          $ref: '#/components/schemas/CogniteExternalId'
    CogniteExternalId:
      description: The external ID provided by the client. Must be unique for the resource type.
      type: string
      maxLength: 255
      example: my.known.id
    DataSetIdEither:
      oneOf:
      - $ref: '#/components/schemas/DataSetInternalId'
      - $ref: '#/components/schemas/DataSetExternalId'
    LabelDefinitionList:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          minItems: 0
          maxItems: 1000
          uniqueItems: true
          items:
            $ref: '#/components/schemas/LabelDefinition'
        nextCursor:
          type: string
          description: The cursor to get the next page of results (if available).
    LabelSelectByExternalId:
      type: object
      title: Select by ExternalId
      properties:
        externalId:
          $ref: '#/components/schemas/CogniteExternalId'
    ExternalLabelDefinition:
      type: object
      required:
      - externalId
      - name
      description: 'A label definition is a globally defined label that can later be attached to resources (e.g., assets). For example, can you define a "Pump" label definition and attach that label to your pump assets.

        '
      properties:
        externalId:
          $ref: '#/components/schemas/CogniteExternalId'
        name:
          description: Name of the label.
          type: string
          minLength: 1
          maxLength: 140
        description:
          description: Description of the label.
          type: string
          maxLength: 500
        dataSetId:
          description: The id of the dataset this label belongs to.
          allOf:
          - $ref: '#/components/schemas/CogniteInternalId'
    LabelDefinitionFilter:
      type: object
      properties:
        filter:
          type: object
          description: Filter on labels definitions with strict matching.
          title: Filter
          properties:
            name:
              description: Returns the label definitions matching that name.
              type: string
              minLength: 1
              maxLength: 140
            externalIdPrefix:
              $ref: '#/components/schemas/ExternalIdPrefixFilter'
            dataSetIds:
              type: array
              maxItems: 1000
              items:
                $ref: '#/components/schemas/DataSetIdEither'
    LabelDefinitionExternalIdList:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          minItems: 1
          maxItems: 1000
          uniqueItems: true
          items:
            $ref: '#/components/schemas/LabelDefinitionExternalId'
    ExternalIdPrefixFilter:
      description: filter external ids starting with the prefix specified
      type: string
      maxLength: 255
  responses:
    LabelDefinitionListResponse:
      description: A list of label definitions.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LabelDefinitionList'
    LabelDefinitionCreateResponse:
      description: A list of label definitions.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LabelDefinitionCreateList'
    EmptyResponse:
      description: Empty response.
      content:
        application/json:
          schema:
            type: object
    ErrorResponse:
      description: The response for a failed request.
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            properties:
              error:
                $ref: '#/components/schemas/Error'
  securitySchemes:
    oidc-token:
      type: http
      scheme: bearer
      bearerFormat: OpenID Connect or OAuth2 token
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
    oauth2-client-credentials:
      type: oauth2
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
      flows:
        clientCredentials:
          tokenUrl: https://your-idps.token.url/
          scopes:
            default: https://{cluster}.cognitedata.com/.default
    oauth2-auth-code:
      type: oauth2
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
      flows:
        authorizationCode:
          authorizationUrl: https://your-idps.authorization.url/
          tokenUrl: https://your-idps.token.url/
          scopes:
            default: https://{cluster}.cognitedata.com/.default
    oauth2-open-industrial-data:
      type: oauth2
      description: Auth flow for Open Industrial Data. Get your client secret from https://hub.cognite.com/open-industrial-data-211.
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/48d5043c-cf70-4c49-881c-c638f5796997/oauth2/v2.0/token
          scopes:
            default: https://api.cognitedata.com/.default
    org-oidc-token:
      type: openIdConnect
      openIdConnectUrl: https://auth.cognite.com/.well-known/openid-configuration
      description: 'Access token issued by the Cognite authorization server, and valid for the target organization. The token must

        be an OpenID Connect token, and it can be obtained by performing an OIDC login flow toward `auth.cognite.com`.

        This is a single URL for all CDF organizations.'
x-tagGroups:
- name: Changelog
  tags:
  - Changelog
- name: Organizations and projects
  tags:
  - Organizations
  - Projects
- name: Identity and access management
  tags:
  - Principals
  - Groups
  - Security categories
  - Sessions
  - Token
  - User profiles
  - Project Deletion Reporting
- name: Data modeling
  tags:
  - Data Modeling
  - Data models
  - Spaces
  - Views
  - Containers
  - Nodes
  - Instances
  - Statistics
  - Streams
  - Records
- name: Asset-centric data model
  tags:
  - Assets
  - Time series
  - Synthetic Time Series
  - Data point subscriptions
  - Events
  - Files
  - Sequences
  - Geospatial
  - Seismic
- name: 3D
  tags:
  - 3D Models
  - 3D Model Revisions
  - 3D Files
  - 3D Asset Mapping
  - 3D Contextualization
  - 3D Jobs
  - 3D Migration
  - 3D Scenes
- name: Contextualization
  tags:
  - Entity matching
  - Entity matching pipelines
  - Engineering diagrams
  - Vision
  - Advanced joins
- name: Cognite AI
  tags:
  - Agents
  - Skills
  - Chat Completions
  - Document AI
  - Models
- name: Documents
  tags:
  - Documents
  - Document preview
- name: Data ingestion
  tags:
  - Raw
  - Extraction Pipelines
  - Extraction Pipelines Runs
  - Extraction Pipelines Config
  - Extractors
- name: Data organization
  tags:
  - Data sets
  - Data domains
  - Data products
  - Rule sets
  - Labels
  - Relationships
  - Annotations
- name: Transformations
  tags:
  - Transformations
  - Transformation Jobs
  - Transformation Schedules
  - Transformation Notifications
  - Query
  - Schema
- name: Functions
  tags:
  - Functions
  - Function calls
  - Function schedules
- name: Hosted Extractors
  tags:
  - Sources
  - Jobs
  - Destinations
  - Mappings
- name: PostgreSQL Gateway
  tags:
  - Postgres Gateway Users
  - Postgres Gateway Tables
- name: SAP Writeback
  tags:
  - SAP Instances
  - SAP Endpoints
  - Schema Mappings
  - Writeback Requests
- name: Data workflows
  tags:
  - Workflows
  - Workflow versions
  - Workflow executions
  - Workflow triggers
  - Tasks
  - Workers
- name: Simulators
  tags:
  - Simulators
  - Simulator Integrations
  - Simulator Models
  - Simulator Routines
  - Simulation Runs
  - Simulator Logs
- name: Units
  tags:
  - Units
  - Unit Systems
- name: ''
  tags:
  - ''
