openapi: 3.2.0
info:
  title: Cognite Spaces API
  description: '# Introduction

    This is the reference documentation for the Cognite API with

    an overview of all the available methods.'
  version: v1
  contact:
    name: Cognite Support
    url: https://support.cognite.com
    email: support@cognite.com
servers:
- url: https://{cluster}.cognitedata.com/api/v1/projects/{project}
  description: The URL for the CDF cluster to connect to
  variables:
    cluster:
      enum:
      - api
      - az-tyo-gp-001
      - az-eastus-1
      - az-power-no-northeurope
      - westeurope-1
      - asia-northeast1-1
      - gc-dsm-gp-001
      default: api
      description: The CDF cluster to connect to
    project:
      default: publicdata
      description: The CDF project name.
security:
- oidc-token:
  - https://{cluster}.cognitedata.com/.default
- oauth2-client-credentials:
  - https://{cluster}.cognitedata.com/.default
- oauth2-open-industrial-data:
  - https://api.cognitedata.com/.default
- oauth2-auth-code:
  - https://{cluster}.cognitedata.com/.default
tags:
- name: Spaces
paths:
  /models/spaces:
    post:
      tags:
      - Spaces
      summary: Create or update spaces
      description: '> **Required capabilities:** `dataModelsAcl:WRITE`


        Add or update (upsert) spaces. For unchanged space specifications, the operation completes without making any changes. We will not update the ```lastUpdatedTime``` value for spaces that remain unchanged.'
      operationId: ApplySpaces
      requestBody:
        description: Spaces to add or update.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceCreateCollection'
        required: true
      x-capability:
      - dataModelsAcl:WRITE
      responses:
        '200':
          $ref: '#/components/responses/SpaceCollectionResponseV3'
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          description: Space conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpsertConflict'
      x-code-samples:
      - lang: Python
        label: Python SDK
        source: 'from cognite.client.data_classes.data_modeling import SpaceApply

          spaces = [SpaceApply(space="mySpace", description="My first space", name="My Space"),

          SpaceApply(space="myOtherSpace", description="My second space", name="My Other Space")]

          res = client.data_modeling.spaces.apply(spaces)

          '
    get:
      tags:
      - Spaces
      summary: List spaces defined in the project
      description: '> **Required capabilities:** `dataModelsAcl:READ`


        List spaces defined in the current project.'
      operationId: listSpacesV3
      parameters:
      - $ref: '#/components/parameters/ReducedLimit'
      - $ref: '#/components/parameters/Cursor'
      - $ref: '#/components/parameters/IncludeGlobal'
      x-capability:
      - dataModelsAcl:READ
      responses:
        '200':
          $ref: '#/components/responses/SpaceCollectionResponseWithCursor'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-code-samples:
      - lang: Python
        label: Python SDK
        source: "space_list = client.data_modeling.spaces.list(limit=5)\n\nfor space in client.data_modeling.spaces:\n    space # do something with the space\n\nfor space_list in client.data_modeling.spaces(chunk_size=2500):\n    space_list # do something with the spaces\n"
  /models/spaces/byids:
    post:
      tags:
      - Spaces
      summary: Retrieve spaces by their space-ids
      description: '> **Required capabilities:** `dataModelsAcl:READ`


        Retrieve up to 100 spaces by specifying their space-ids.'
      operationId: bySpaceIdsSpaces
      requestBody:
        description: List of space-ids for the spaces to return.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListOfSpaceIdsRequest'
        required: true
      x-capability:
      - dataModelsAcl:READ
      responses:
        '200':
          $ref: '#/components/responses/SpaceCollectionResponseV3'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-code-samples:
      - lang: Python
        label: Python SDK
        source: 'res = client.data_modeling.spaces.retrieve(spaces=''mySpace'')


          res = client.data_modeling.spaces.retrieve(spaces=["MySpace", "MyAwesomeSpace", "MyOtherSpace"])

          '
  /models/spaces/delete:
    post:
      tags:
      - Spaces
      summary: Delete spaces
      description: '> **Required capabilities:** `dataModelsAcl:WRITE`


        Delete one or more spaces, maximum 100 spaces at a time.


        Only empty spaces can be deleted.'
      operationId: deleteSpacesV3
      requestBody:
        description: List of space-ids for spaces to delete.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListOfSpaceIdsRequest'
        required: true
      x-capability:
      - dataModelsAcl:WRITE
      responses:
        '200':
          $ref: '#/components/responses/ListOfSpaceIdsResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-code-samples:
      - lang: Python
        label: Python SDK
        source: 'client.data_modeling.spaces.delete(spaces=["mySpace", "myOtherSpace"])

          '
components:
  schemas:
    Error:
      type: object
      required:
      - code
      - message
      description: Cognite API error.
      properties:
        code:
          type: integer
          description: HTTP status code.
          format: int32
          example: 401
        message:
          type: string
          description: Error message.
          example: Could not authenticate.
        missing:
          type: array
          description: List of lookup objects that do not match any results.
          items:
            type: object
            additionalProperties: true
        duplicated:
          type: array
          description: List of objects that are not unique.
          items:
            type: object
            additionalProperties: true
    ListOfSpaceIdsRequest:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          minItems: 1
          maxItems: 100
          items:
            type: object
            required:
            - space
            properties:
              space:
                description: Ids for the spaces to perform operations on
                allOf:
                - $ref: '#/components/schemas/SpaceSpecification'
    SpaceSpecification:
      type: string
      pattern: ^[a-zA-Z][a-zA-Z0-9_-]{0,41}[a-zA-Z0-9]?$
      minLength: 1
      maxLength: 43
    NextCursorV3:
      description: The cursor value used to return (paginate to) the next page of results, when more data is available.
      type: string
    EpochTimestamp:
      description: The number of milliseconds since 00:00:00 Thursday, 1 January 1970, Coordinated Universal Time (UTC), minus leap seconds.
      type: integer
      minimum: 0
      format: int64
      example: 1730204346000
    SpaceCreateCollection:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          description: List of spaces to create/update
          minItems: 1
          maxItems: 100
          items:
            $ref: '#/components/schemas/SpaceCreateDefinition'
    SpaceCreateDefinition:
      type: object
      required:
      - space
      properties:
        space:
          type: string
          description: "The Space identifier (id).\n\n\nNote that we have reserved the use of certain space ids.  These reserved spaces are:\n * `space`\n * `cdf`\n * `dms`\n * `pg3`\n * `shared`\n * `system`\n * `node`\n * `edge`\n "
          pattern: (?!^(space|cdf|dms|pg3|shared|system|node|edge)$)(^[a-zA-Z][a-zA-Z0-9_-]{0,41}[a-zA-Z0-9]?$)
          minLength: 1
          maxLength: 43
        description:
          type: string
          description: Used to describe the space you're defining.
          maxLength: 1024
        name:
          type: string
          description: Human-readable name for the space.
          maxLength: 255
    SpaceDefinition:
      allOf:
      - $ref: '#/components/schemas/SpaceCreateDefinition'
      - type: object
        required:
        - createdTime
        - lastUpdatedTime
        - isGlobal
        properties:
          createdTime:
            $ref: '#/components/schemas/EpochTimestamp'
          lastUpdatedTime:
            $ref: '#/components/schemas/EpochTimestamp'
          isGlobal:
            type: boolean
            description: Is this a global space.
    UpsertConflict:
      type: object
      required:
      - error
      properties:
        error:
          type: object
          description: Details about the error caused by the upsert/update.
          required:
          - code
          - message
          properties:
            code:
              type: integer
              description: The HTTP status code returned
              format: int32
              example: 409
            message:
              type: string
              description: The error message returned from the service.
            isAutoRetryable:
              type: boolean
              description: Whether or not the error is auto-retryable. If present and true, the client can automatically retry the request after some delay.
  parameters:
    ReducedLimit:
      name: limit
      description: Limit the number of results returned. The largest result-set returned by the server will be 1000 items, even if you specify a higher limit.
      in: query
      schema:
        type: integer
        default: 10
        minimum: 1
        maximum: 1000
    IncludeGlobal:
      name: includeGlobal
      in: query
      description: If the global items of the entity should be returned. Defaults to false which excludes global items.
      schema:
        type: boolean
        default: false
    Cursor:
      name: cursor
      description: 'Cursor for paging through results. In general, if a response contains a `nextCursor`

        property, it means that there may be more results, and you should pass that value as the

        `cursor` parameter in the next request.


        Note that the cursor may or may not be encrypted, but either way, it is not intended to be

        decoded. Its internal structure is not a part of the public API, and may change without

        notice. You should treat it as an opaque string and not attempt to craft your own cursors.

        '
      in: query
      schema:
        type: string
        example: 4zj0Vy2fo0NtNMb229mI9r1V3YG5NBL752kQz1cKtwo
  responses:
    ErrorResponse:
      description: The response for a failed request.
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            properties:
              error:
                $ref: '#/components/schemas/Error'
    SpaceCollectionResponseWithCursor:
      description: List of spaces
      content:
        application/json:
          schema:
            type: object
            required:
            - items
            properties:
              items:
                type: array
                description: List of spaces
                items:
                  $ref: '#/components/schemas/SpaceDefinition'
              nextCursor:
                $ref: '#/components/schemas/NextCursorV3'
    SpaceCollectionResponseV3:
      description: List of spaces
      content:
        application/json:
          schema:
            type: object
            required:
            - items
            properties:
              items:
                type: array
                description: List of spaces
                items:
                  $ref: '#/components/schemas/SpaceDefinition'
    ListOfSpaceIdsResponse:
      description: List of space id(s) affected by the request
      content:
        application/json:
          schema:
            type: object
            required:
            - items
            properties:
              items:
                type: array
                minItems: 1
                maxItems: 100
                items:
                  type: object
                  required:
                  - space
                  properties:
                    space:
                      description: List of space ids for the requested item(s)
                      allOf:
                      - $ref: '#/components/schemas/SpaceSpecification'
  securitySchemes:
    oidc-token:
      type: http
      scheme: bearer
      bearerFormat: OpenID Connect or OAuth2 token
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
    oauth2-client-credentials:
      type: oauth2
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
      flows:
        clientCredentials:
          tokenUrl: https://your-idps.token.url/
          scopes:
            default: https://{cluster}.cognitedata.com/.default
    oauth2-auth-code:
      type: oauth2
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
      flows:
        authorizationCode:
          authorizationUrl: https://your-idps.authorization.url/
          tokenUrl: https://your-idps.token.url/
          scopes:
            default: https://{cluster}.cognitedata.com/.default
    oauth2-open-industrial-data:
      type: oauth2
      description: Auth flow for Open Industrial Data. Get your client secret from https://hub.cognite.com/open-industrial-data-211.
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/48d5043c-cf70-4c49-881c-c638f5796997/oauth2/v2.0/token
          scopes:
            default: https://api.cognitedata.com/.default
    org-oidc-token:
      type: openIdConnect
      openIdConnectUrl: https://auth.cognite.com/.well-known/openid-configuration
      description: 'Access token issued by the Cognite authorization server, and valid for the target organization. The token must

        be an OpenID Connect token, and it can be obtained by performing an OIDC login flow toward `auth.cognite.com`.

        This is a single URL for all CDF organizations.'
x-tagGroups:
- name: Changelog
  tags:
  - Changelog
- name: Organizations and projects
  tags:
  - Organizations
  - Projects
- name: Identity and access management
  tags:
  - Principals
  - Groups
  - Security categories
  - Sessions
  - Token
  - User profiles
  - Project Deletion Reporting
- name: Data modeling
  tags:
  - Data Modeling
  - Data models
  - Spaces
  - Views
  - Containers
  - Nodes
  - Instances
  - Statistics
  - Streams
  - Records
- name: Asset-centric data model
  tags:
  - Assets
  - Time series
  - Synthetic Time Series
  - Data point subscriptions
  - Events
  - Files
  - Sequences
  - Geospatial
  - Seismic
- name: 3D
  tags:
  - 3D Models
  - 3D Model Revisions
  - 3D Files
  - 3D Asset Mapping
  - 3D Contextualization
  - 3D Jobs
  - 3D Migration
  - 3D Scenes
- name: Contextualization
  tags:
  - Entity matching
  - Entity matching pipelines
  - Engineering diagrams
  - Vision
  - Advanced joins
- name: Cognite AI
  tags:
  - Agents
  - Skills
  - Chat Completions
  - Document AI
  - Models
- name: Documents
  tags:
  - Documents
  - Document preview
- name: Data ingestion
  tags:
  - Raw
  - Extraction Pipelines
  - Extraction Pipelines Runs
  - Extraction Pipelines Config
  - Extractors
- name: Data organization
  tags:
  - Data sets
  - Data domains
  - Data products
  - Rule sets
  - Labels
  - Relationships
  - Annotations
- name: Transformations
  tags:
  - Transformations
  - Transformation Jobs
  - Transformation Schedules
  - Transformation Notifications
  - Query
  - Schema
- name: Functions
  tags:
  - Functions
  - Function calls
  - Function schedules
- name: Hosted Extractors
  tags:
  - Sources
  - Jobs
  - Destinations
  - Mappings
- name: PostgreSQL Gateway
  tags:
  - Postgres Gateway Users
  - Postgres Gateway Tables
- name: SAP Writeback
  tags:
  - SAP Instances
  - SAP Endpoints
  - Schema Mappings
  - Writeback Requests
- name: Data workflows
  tags:
  - Workflows
  - Workflow versions
  - Workflow executions
  - Workflow triggers
  - Tasks
  - Workers
- name: Simulators
  tags:
  - Simulators
  - Simulator Integrations
  - Simulator Models
  - Simulator Routines
  - Simulation Runs
  - Simulator Logs
- name: Units
  tags:
  - Units
  - Unit Systems
- name: ''
  tags:
  - ''
