openapi: 3.2.0
info:
  title: Cognite Security categories API
  description: '# Introduction

    This is the reference documentation for the Cognite API with

    an overview of all the available methods.'
  version: v1
  contact:
    name: Cognite Support
    url: https://support.cognite.com
    email: support@cognite.com
servers:
- url: https://{cluster}.cognitedata.com/api/v1/projects/{project}
  description: The URL for the CDF cluster to connect to
  variables:
    cluster:
      enum:
      - api
      - az-tyo-gp-001
      - az-eastus-1
      - az-power-no-northeurope
      - westeurope-1
      - asia-northeast1-1
      - gc-dsm-gp-001
      default: api
      description: The CDF cluster to connect to
    project:
      default: publicdata
      description: The CDF project name.
security:
- oidc-token:
  - https://{cluster}.cognitedata.com/.default
- oauth2-client-credentials:
  - https://{cluster}.cognitedata.com/.default
- oauth2-open-industrial-data:
  - https://api.cognitedata.com/.default
- oauth2-auth-code:
  - https://{cluster}.cognitedata.com/.default
tags:
- name: Security categories
  description: 'Manage security categories for a specific project.

    Security categories can be used to restrict access to a resource.

    Applying a security category to a resource means that only principals (users or service accounts) that also have this security category can access the resource.

    To learn more about security categories please read this page.'
paths:
  /securitycategories:
    get:
      tags:
      - Security categories
      summary: List security categories
      description: '> **Required capabilities:** `securityCategoriesAcl:LIST`


        Retrieves a list of all security categories for a project.'
      operationId: getSecurityCategories
      parameters:
      - name: sort
        in: query
        description: Sort descending or ascending.
        schema:
          type: string
          enum:
          - ASC
          - DESC
          default: ASC
      - name: cursor
        in: query
        description: Cursor to use for paging through results.
        schema:
          type: string
      - name: limit
        in: query
        description: Return up to this many results. Maximum is 1000. Default is 25.
        schema:
          maximum: 1000
          type: integer
          format: int32
          default: 25
      responses:
        '200':
          description: A list of security categories.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityCategoryWithCursorResponse'
      x-capability:
      - securityCategoriesAcl:LIST
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: 'const securityCategories = await client.securityCategories.list({ sort: ''ASC'' });'
      - lang: Python
        label: Python SDK
        source: 'res = client.iam.security_categories.list()

          '
      - lang: Java
        label: Java SDK
        source: "List<SecurityCategory> listSecurityCategoriesResults = new ArrayList<>(); \nclient.securityCategories(). \n          list(Request.create()) \n          .forEachRemaining(labels -> listSecurityCategoriesResults.addAll(labels)); \n\n "
    post:
      tags:
      - Security categories
      summary: Create security categories
      description: '> **Required capabilities:** `securityCategoriesAcl:CREATE`


        Creates security categories with the given names. Duplicate names in the request are ignored.

        If a security category with one of the provided names exists already, then the request will fail and no security categories are created.'
      operationId: createSecurityCategories
      requestBody:
        description: List of categories to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataSecurityCategorySpecDTO'
        required: true
      responses:
        '201':
          description: A list of security categories.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityCategoryResponse'
      x-capability:
      - securityCategoriesAcl:CREATE
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: "const securityCategories = [\n  { name: 'Admins' },\n  { name: 'Developers' },\n];\nconst createdSecurityCategories = await client.securityCategories.create(securityCategories);"
      - lang: Python
        label: Python SDK
        source: 'from cognite.client.data_classes import SecurityCategoryWrite

          my_category = SecurityCategoryWrite(name="My Category")

          res = client.iam.security_categories.create(my_category)

          '
      - lang: Java
        label: Java SDK
        source: "List<SecurityCategory> createSecurityCategoriesList = \n       List.of(SecurityCategory.newBuilder().setName(\"Name\").build()); \nclient.securityCategories().create(createSecurityCategoriesList); \n\n "
  /securitycategories/delete:
    post:
      tags:
      - Security categories
      summary: Delete security categories
      description: '> **Required capabilities:** `securityCategoriesAcl:DELETE`


        Deletes the security categories that match the provided IDs.

        If any of the provided IDs does not belong to an existing security category, then the request will fail and no security categories are deleted.'
      operationId: deleteSecurityCategories
      requestBody:
        description: List of security category IDs to delete.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataLong'
        required: true
      responses:
        '200':
          $ref: '#/components/responses/EmptyResponse'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - securityCategoriesAcl:DELETE
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: await client.securityCategories.delete([123, 456]);
      - lang: Python
        label: Python SDK
        source: 'client.iam.security_categories.delete(1)

          '
      - lang: Java
        label: Java SDK
        source: "List<SecurityCategory> deleteItemsResults = \n          client.securityCategories() \n          .delete(listSecurityCategoriesResults); \n\n "
components:
  schemas:
    SecurityCategoryDTO:
      required:
      - name
      - id
      type: object
      properties:
        name:
          type: string
          description: Name of the security category
          example: Guarded by vendor x
        id:
          type: integer
          description: ID of the security category
          format: int64
    Error:
      type: object
      required:
      - code
      - message
      description: Cognite API error.
      properties:
        code:
          type: integer
          description: HTTP status code.
          format: int32
          example: 401
        message:
          type: string
          description: Error message.
          example: Could not authenticate.
        missing:
          type: array
          description: List of lookup objects that do not match any results.
          items:
            type: object
            additionalProperties: true
        duplicated:
          type: array
          description: List of objects that are not unique.
          items:
            type: object
            additionalProperties: true
    DataSecurityCategorySpecDTO:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          minLength: 1
          items:
            $ref: '#/components/schemas/SecurityCategorySpecDTO'
    DataLong:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          example:
          - 23872937137
          - 1238712837
          - 128371973
          minItems: 1
          uniqueItems: true
          items:
            type: integer
            format: int64
    SecurityCategorySpecDTO:
      required:
      - name
      type: object
      properties:
        name:
          type: string
          description: Name of the security category
          example: Guarded by vendor x
    SecurityCategoryResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SecurityCategoryDTO'
    SecurityCategoryWithCursorResponse:
      type: object
      required:
      - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SecurityCategoryDTO'
        nextCursor:
          type: string
          description: Cursor to get the next page of results (if available).
      description: A list of objects along with possible cursors to get the next page of results
  responses:
    ErrorResponse:
      description: The response for a failed request.
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            properties:
              error:
                $ref: '#/components/schemas/Error'
    EmptyResponse:
      description: Empty response.
      content:
        application/json:
          schema:
            type: object
  securitySchemes:
    oidc-token:
      type: http
      scheme: bearer
      bearerFormat: OpenID Connect or OAuth2 token
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
    oauth2-client-credentials:
      type: oauth2
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
      flows:
        clientCredentials:
          tokenUrl: https://your-idps.token.url/
          scopes:
            default: https://{cluster}.cognitedata.com/.default
    oauth2-auth-code:
      type: oauth2
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
      flows:
        authorizationCode:
          authorizationUrl: https://your-idps.authorization.url/
          tokenUrl: https://your-idps.token.url/
          scopes:
            default: https://{cluster}.cognitedata.com/.default
    oauth2-open-industrial-data:
      type: oauth2
      description: Auth flow for Open Industrial Data. Get your client secret from https://hub.cognite.com/open-industrial-data-211.
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/48d5043c-cf70-4c49-881c-c638f5796997/oauth2/v2.0/token
          scopes:
            default: https://api.cognitedata.com/.default
    org-oidc-token:
      type: openIdConnect
      openIdConnectUrl: https://auth.cognite.com/.well-known/openid-configuration
      description: 'Access token issued by the Cognite authorization server, and valid for the target organization. The token must

        be an OpenID Connect token, and it can be obtained by performing an OIDC login flow toward `auth.cognite.com`.

        This is a single URL for all CDF organizations.'
x-tagGroups:
- name: Changelog
  tags:
  - Changelog
- name: Organizations and projects
  tags:
  - Organizations
  - Projects
- name: Identity and access management
  tags:
  - Principals
  - Groups
  - Security categories
  - Sessions
  - Token
  - User profiles
  - Project Deletion Reporting
- name: Data modeling
  tags:
  - Data Modeling
  - Data models
  - Spaces
  - Views
  - Containers
  - Nodes
  - Instances
  - Statistics
  - Streams
  - Records
- name: Asset-centric data model
  tags:
  - Assets
  - Time series
  - Synthetic Time Series
  - Data point subscriptions
  - Events
  - Files
  - Sequences
  - Geospatial
  - Seismic
- name: 3D
  tags:
  - 3D Models
  - 3D Model Revisions
  - 3D Files
  - 3D Asset Mapping
  - 3D Contextualization
  - 3D Jobs
  - 3D Migration
  - 3D Scenes
- name: Contextualization
  tags:
  - Entity matching
  - Entity matching pipelines
  - Engineering diagrams
  - Vision
  - Advanced joins
- name: Cognite AI
  tags:
  - Agents
  - Skills
  - Chat Completions
  - Document AI
  - Models
- name: Documents
  tags:
  - Documents
  - Document preview
- name: Data ingestion
  tags:
  - Raw
  - Extraction Pipelines
  - Extraction Pipelines Runs
  - Extraction Pipelines Config
  - Extractors
- name: Data organization
  tags:
  - Data sets
  - Data domains
  - Data products
  - Rule sets
  - Labels
  - Relationships
  - Annotations
- name: Transformations
  tags:
  - Transformations
  - Transformation Jobs
  - Transformation Schedules
  - Transformation Notifications
  - Query
  - Schema
- name: Functions
  tags:
  - Functions
  - Function calls
  - Function schedules
- name: Hosted Extractors
  tags:
  - Sources
  - Jobs
  - Destinations
  - Mappings
- name: PostgreSQL Gateway
  tags:
  - Postgres Gateway Users
  - Postgres Gateway Tables
- name: SAP Writeback
  tags:
  - SAP Instances
  - SAP Endpoints
  - Schema Mappings
  - Writeback Requests
- name: Data workflows
  tags:
  - Workflows
  - Workflow versions
  - Workflow executions
  - Workflow triggers
  - Tasks
  - Workers
- name: Simulators
  tags:
  - Simulators
  - Simulator Integrations
  - Simulator Models
  - Simulator Routines
  - Simulation Runs
  - Simulator Logs
- name: Units
  tags:
  - Units
  - Unit Systems
- name: ''
  tags:
  - ''
